APP_PASSWORD='password que obtuvimos recien'
SENDER='nuestro email'
SUBJECT_FROM='nuestro nombre o lo que queramos realmente'
RECIPIENTS_1='email de a quien molestar 1'
RECIPIENTS_2='email de a quien molestar 2'
RECIPIENTS_3='email de a quien molestar 3'
